In [1]:
import numpy as np
array = np.array([34, 12, 7, 56, 89, 22, 457])
sorted_array = np.sort(array)
print("Original array:")
print(array)
print("Sorted array:")
print(sorted_array)

Original array:
[ 34  12   7  56  89  22 457]
Sorted array:
[  7  12  22  34  56  89 457]


In [3]:
import numpy as np
a = np.array([[3, 10, 2], [1, 5, 7], [6, 7, 5]])
print(np.sort(a))
array4 = np.sort(a, axis=0)
print(array4)
a1 = np.sort(a, axis=None)
print(a1)
a2 = np.sort(a, axis=1)
print(a2)

[[ 2  3 10]
 [ 1  5  7]
 [ 5  6  7]]
[[ 1  5  2]
 [ 3  7  5]
 [ 6 10  7]]
[ 1  2  3  5  5  6  7  7 10]
[[ 2  3 10]
 [ 1  5  7]
 [ 5  6  7]]


In [7]:
import pandas as pd
l = [1, 2, 3]
s = pd.Series(l)
print(s)
data = {"Name": ["Diya", "Tayal", "Kayal"],
        "Age": [19, 18, 21],
        "Study": ["BTECH", "MBA", "BSC"]}
df = pd.DataFrame(data)
print("DataFrame:")
print(df)

0    1
1    2
2    3
dtype: int64
DataFrame:
    Name  Age  Study
0   Diya   19  BTECH
1  Tayal   18    MBA
2  Kayal   21    BSC


In [9]:
import heapq
def uniform_cost_search(graph, start, goal):
    priority_queue = [(0, start, [])]
    visited = set()
    while priority_queue:
        cost, node, path = heapq.heappop(priority_queue)
        if node in visited:
            continue
        path = path + [node]
        visited.add(node)
        if node == goal:
            return cost, path
        for neighbour, edge_cost in graph.get(node, []):
            if neighbour not in visited:
                heapq.heappush(priority_queue, (cost + edge_cost, neighbour, path))
graph = {
    'A': [('B', 8), ('C', 3)],
    'B': [('E', 10), ('D', 2)],
    'C': [('F', 6), ('G', 7)],
    'F': [('E', 2), ('G', 1)]
}
start_node = 'A'
goal_node = 'E'
cost, path = uniform_cost_search(graph, start_node, goal_node)
print("Least cost path from", start_node, "to", goal_node, ":", path)
print("Total cost:", cost)

Least cost path from A to E : ['A', 'C', 'F', 'E']
Total cost: 11


In [16]:
import heapq
def astar_search(start, goal, graph, heuristic):
    open_list = [(0, start, [])]    
    while open_list:
        cost, current_node, path = heapq.heappop(open_list)
        path = path + [current_node]
        if current_node == goal:
                    return path, cost        
        for neighbor, edge_cost in graph.get(current_node, []):
            heapq.heappush(open_list, (cost + edge_cost + heuristic[neighbor], neighbor, path))    
    return None
graph = {
    'A': [('B', 6), ('C', 3)],
    'B': [('D', 2), ('E', 4)],
    'C': [('F', 10)],
    'D': [('G', 4)],
    'E': [('G', 1)],
    'F': [('G', 2)]
}
heuristic = {
    'A': 7, 'B': 6, 'C': 5, 'D': 4, 'E': 3, 'F': 6, 'G': 0
}
start_node = 'A'
goal_node = 'G'
path, total_cost = astar_search(start_node, goal_node, graph, heuristic)
print("Least cost path from", start_node, "to", goal_node, "is", path)
print("Total cost:", total_cost)

Least cost path from A to G is ['A', 'B', 'E', 'G']
Total cost: 20


In [53]:
import random
def objective_function(x):
    return -x**2 + 4*x
def hill_climb(start_x, step_size=0.1, max_iterations=100):
    current_x = start_x
    current_value = objective_function(current_x)    
    for _ in range(max_iterations):
        neighbours = [current_x + step_size, current_x - step_size]
        best_neighbour = max(neighbours, key=objective_function)
        best_neighbour_value = objective_function(best_neighbour)        
        if best_neighbour_value > current_value:
            current_x, current_value = best_neighbour, best_neighbour_value
        else:
            break    
    return current_x, current_value
start_point = random.uniform(-10, 10)
best_x, best_value = hill_climb(start_point)
print(f"Optimal x: {best_x:.4f}")
print(f"Optimal value: {best_value:.4f}")

Optimal x: 1.9511
Optimal value: 3.9976


In [55]:
MAX, MIN = 1000, -1000
def minimax(depth, nodeIndex, maximizingPlayer, values, alpha, beta):
    if depth == 3:
        return values[nodeIndex]
    if maximizingPlayer:
        best = MIN
        for i in range(2):
            val = minimax(depth + 1, nodeIndex * 2 + i, False, values, alpha, beta)
            best = max(best, val)
            alpha = max(alpha, best)
            if beta <= alpha:
                break
        return best
    else:
        best = MAX
        for i in range(2):
            val = minimax(depth + 1, nodeIndex * 2 + i, True, values, alpha, beta)
            best = min(best, val)
            beta = min(beta, best)
            if beta <= alpha:
                break
        return best
if __name__ == "__main__":
    values = [3, 5, 6, 9, 1, 2, 0, -1]
    print("The optimal value is:", minimax(0, 0, True, values, MAX, MIN))



The optimal value is: 3


In [101]:
N = 8
def printSolution(board):
    for i in range(N):
        for j in range(N):
            print(board[i][j], end=' ')
        print()
def isSafe(board, row, col):
    for i in range(col):
        if board[row][i] == 1:
            return False    
    for i, j in zip(range(row, -1, -1), range(col, -1, -1)):
        if board[i][j] == 1:
            return False   
    for i, j in zip(range(row, N, 1), range(col, -1, -1)):
        if board[i][j] == 1:
            return False
    return True
def solveNQUtil(board, col):
    if col >= N:
        return True

    for i in range(N):
        if isSafe(board, i, col):
            board[i][col] = 1
            if solveNQUtil(board, col + 1) == True:
                return True
            board[i][col] = 0  # Backtrack
    return False
def solveNQ():
    board = [ [0 for _ in range(N)] for _ in range(N) ]
    if solveNQUtil(board, 0) == False:
        print ("Solution does not exist")
        return False
    printSolution(board)
    return True
solveNQ()

1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 0 
0 0 0 0 1 0 0 0 
0 0 0 0 0 0 0 1 
0 1 0 0 0 0 0 0 
0 0 0 1 0 0 0 0 
0 0 0 0 0 1 0 0 
0 0 1 0 0 0 0 0 


True